port: 17880
prometheus_port: 16789
bind_addresses: [127.0.0.1]
key_file: keys.yaml
room:
  auto_create: false
  max_participants: 16
rtc:
  node_ip: 127.0.0.1
  use_external_ip: false
  tcp_port: 17881
  udp_port: 17882
