// Captured from the pinned real CLIs (see scripts/check_runtime_cli_contract.sh), no account:
// `<cli> <command> --help` stdout captured on 2026-10-08 with Claude Code 2.1.285 (linux-x64-musl,
// sha256 7b4414af1bc06eb6d91730759bd01c4c02a4976d0b8526237e9a6d8c33eaf102) and Codex rust-v0.160.1
// (x86_64-unknown-linux-musl, sha256 9226581be592d18f7e7f740a352fdb63aa61e45e39f7eb9b09d3888c84bba33f),
// run in `docker run --network none`. A new login method or option in a pinned release changes the
// real output and fails the contract check; the fakes print these same texts, so one table covers both.
// To refresh after a pin changes: run the real help again and replace the lines.

export type GoldenClient = 'claude_code' | 'codex';

export const GOLDEN_HELP: Record<GoldenClient, Record<string, string>> = {
  claude_code: {
    "auth --help": [
      "Usage: claude auth [options] [command]",
      "",
      "Manage authentication",
      "",
      "Options:",
      "  -h, --help        Display help for command",
      "",
      "Commands:",
      "  help [command]    display help for command",
      "  login [options]   Sign in to your Anthropic account",
      "  logout            Log out from your Anthropic account",
      "  status [options]  Show authentication status",
    ].join('\n') + '\n',
    "auth login --help": [
      "Usage: claude auth login [options]",
      "",
      "Sign in to your Anthropic account",
      "",
      "Options:",
      "  --claudeai       Use Claude subscription (default)",
      "  --console        Use Anthropic Console (API usage billing) instead of Claude",
      "                   subscription",
      "  --email <email>  Pre-populate email address on the login page",
      "  -h, --help       Display help for command",
      "  --sso            Force SSO login flow",
    ].join('\n') + '\n',
    "auth status --help": [
      "Usage: claude auth status [options]",
      "",
      "Show authentication status",
      "",
      "Options:",
      "  -h, --help  Display help for command",
      "  --json      Output as JSON (default)",
      "  --text      Output as human-readable text",
    ].join('\n') + '\n',
    "auth logout --help": [
      "Usage: claude auth logout [options]",
      "",
      "Log out from your Anthropic account",
      "",
      "Options:",
      "  -h, --help  Display help for command",
    ].join('\n') + '\n',
  },
  codex: {
    "login --help": [
      "Manage login",
      "",
      "Usage: codex login [OPTIONS] [COMMAND]",
      "",
      "Commands:",
      "  status  Show login status",
      "  help    Print this message or the help of the given subcommand(s)",
      "",
      "Options:",
      "  -c, --config <key=value>",
      "          Override a configuration value that would otherwise be loaded from `~/.codex/config.toml`.",
      "          Use a dotted path (`foo.bar.baz`) to override nested values. The `value` portion is parsed",
      "          as TOML. If it fails to parse as TOML, the raw string is used as a literal.",
      "          ",
      "          Examples: - `-c model=\"o3\"` - `-c 'sandbox_permissions=[\"disk-full-read-access\"]'` - `-c",
      "          shell_environment_policy.inherit=all`",
      "",
      "      --with-api-key",
      "          Read the API key from stdin (e.g. `printenv OPENAI_API_KEY | codex login --with-api-key`)",
      "",
      "      --enable <FEATURE>",
      "          Enable a feature (repeatable). Equivalent to `-c features.<name>=true`",
      "",
      "      --with-access-token",
      "          Read the access token from stdin (e.g. `printenv CODEX_ACCESS_TOKEN | codex login",
      "          --with-access-token`)",
      "",
      "      --disable <FEATURE>",
      "          Disable a feature (repeatable). Equivalent to `-c features.<name>=false`",
      "",
      "      --device-auth",
      "          ",
      "",
      "  -h, --help",
      "          Print help (see a summary with '-h')",
    ].join('\n') + '\n',
    "login status --help": [
      "Show login status",
      "",
      "Usage: codex login status [OPTIONS]",
      "",
      "Options:",
      "  -c, --config <key=value>",
      "          Override a configuration value that would otherwise be loaded from `~/.codex/config.toml`.",
      "          Use a dotted path (`foo.bar.baz`) to override nested values. The `value` portion is parsed",
      "          as TOML. If it fails to parse as TOML, the raw string is used as a literal.",
      "          ",
      "          Examples: - `-c model=\"o3\"` - `-c 'sandbox_permissions=[\"disk-full-read-access\"]'` - `-c",
      "          shell_environment_policy.inherit=all`",
      "",
      "      --enable <FEATURE>",
      "          Enable a feature (repeatable). Equivalent to `-c features.<name>=true`",
      "",
      "      --disable <FEATURE>",
      "          Disable a feature (repeatable). Equivalent to `-c features.<name>=false`",
      "",
      "  -h, --help",
      "          Print help (see a summary with '-h')",
    ].join('\n') + '\n',
    "logout --help": [
      "Remove stored authentication credentials",
      "",
      "Usage: codex logout [OPTIONS]",
      "",
      "Options:",
      "  -c, --config <key=value>",
      "          Override a configuration value that would otherwise be loaded from `~/.codex/config.toml`.",
      "          Use a dotted path (`foo.bar.baz`) to override nested values. The `value` portion is parsed",
      "          as TOML. If it fails to parse as TOML, the raw string is used as a literal.",
      "          ",
      "          Examples: - `-c model=\"o3\"` - `-c 'sandbox_permissions=[\"disk-full-read-access\"]'` - `-c",
      "          shell_environment_policy.inherit=all`",
      "",
      "      --enable <FEATURE>",
      "          Enable a feature (repeatable). Equivalent to `-c features.<name>=true`",
      "",
      "      --disable <FEATURE>",
      "          Disable a feature (repeatable). Equivalent to `-c features.<name>=false`",
      "",
      "  -h, --help",
      "          Print help (see a summary with '-h')",
    ].join('\n') + '\n',
  },
};
