import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { after, test } from 'node:test';
import { grantProject, liveInvitationUseCases } from '@flux/core';
import type { Conversation, InboxItem, InboxResponse } from '@flux/contracts';
import { liveInvitationStore } from '../../apps/server/src/live/invitations.js';
import { liveSessionStore } from '../../apps/server/src/live/store.js';
import { db, pool } from './support/db.js';
import { addMember, expectStatus, grant, person, project, workspace, type Person } from './support/people.js';
import { waitFor } from './support/push.js';

// A live invitation becomes one quiet inbox signal for its recipient (#62), generated by the
// running worker from the committed `project.live_invited.v1` event. Invitations are created
// in-process (the Compose API has no SFU configured, so live routes are not registered there).

const invitations = liveInvitationUseCases(liveInvitationStore(db));
const human = (someone: Person) => ({ kind: 'human' as const, id: someone.id });

async function inbox(someone: Person) {
  return (expectStatus(await someone.browser.request('GET', '/api/v1/inbox'), 200) as InboxResponse).items;
}

async function invitationRows(userId: string) {
  return (await pool.query(`SELECT id, reason, url, in_inbox, source_type, source_id FROM notifications
    WHERE user_id = $1 AND reason = 'invitation'`, [userId])).rows as { id: string; url: string; in_inbox: boolean }[];
}

async function generatorCaughtUp() {
  const { rows } = await pool.query('SELECT max(seq) AS seq FROM events');
  const target = Number(rows[0].seq);
  await waitFor(async () => Number((await pool.query("SELECT seq FROM notification_cursor WHERE id = 'generator'")).rows[0].seq) >= target,
    'the generator to catch up');
}

async function fixture(label: string, recipients: string[]) {
  const owner = await person(`${label}-owner`);
  const ws = await workspace(owner, label);
  const place = await project(owner, ws.id, `${label} project`, 'restricted');
  const people: Record<string, Person> = {};
  for (const name of recipients) {
    people[name] = await person(`${label}-${name}`);
    await addMember(owner, ws.id, people[name]!, 'member');
    await grant(owner, place.id, people[name]!, 'viewer');
  }
  const conversation = expectStatus(await owner.browser.request('POST', `/api/v1/projects/${place.id}/conversations`, {
    body: { body: `${label}: walk through the harbour permit before Friday`, clientMessageId: randomUUID() },
  }), 201) as Conversation;
  const anchor = { type: 'conversation' as const, id: conversation.id };
  const session = await liveSessionStore(db).createOrGet(human(owner), place.id, anchor, randomUUID(), async () => {});
  return { owner, ws, place, people, anchor, session };
}

test('a live invitation reaches only its recipient, once, with who, where and the exact link', async () => {
  const label = 'live-invite-notify';
  const f = await fixture(label, ['recipient']);
  const recipient = f.people.recipient!;
  const first = await invitations.invite(human(f.owner), f.session.id, recipient.id);
  const again = await invitations.invite(human(f.owner), f.session.id, recipient.id);
  assert.equal(again.id, first.id);
  const url = `/projects/${f.place.id}/live/${f.session.id}?invitation=${first.id}`;

  const item = await waitFor(async () => (await inbox(recipient)).find((entry: InboxItem) => entry.url === url), 'the invitation in the inbox');
  assert.equal(item.reason, 'invitation');
  assert.equal(item.title, `${label}-owner invited you to work together`);
  assert.equal(item.body, `On “${label}: walk through the harbour permit before Friday” in ${label} project`);
  assert.deepEqual(item.source, { workspaceId: f.ws.id, type: 'project', id: f.place.id });

  // A third invite after generation still changes nothing.
  await invitations.invite(human(f.owner), f.session.id, recipient.id);
  await generatorCaughtUp();
  const events = await pool.query(`SELECT data FROM events WHERE kind = 'project.live_invited.v1' AND data->>'sessionId' = $1`, [f.session.id]);
  assert.equal(events.rows.length, 1, 'one event per invitation, never per repeated invite');
  assert.deepEqual(Object.keys(events.rows[0].data).sort(), ['invitationId', 'recipientId', 'sessionId']);
  assert.deepEqual(events.rows[0].data, { sessionId: f.session.id, invitationId: first.id, recipientId: recipient.id });
  const rows = await invitationRows(recipient.id);
  assert.equal(rows.length, 1);
  assert.equal(rows[0]!.url, url);
  assert.equal((await inbox(recipient)).filter((entry) => entry.reason === 'invitation').length, 1);
  assert.deepEqual(await invitationRows(f.owner.id), [], 'the inviter hears nothing of their own invitation');
});

test('an invitation that no longer applies when the worker reaches it notifies nobody; inbox-off is respected', async () => {
  const label = 'live-invite-stale';
  const f = await fixture(label, ['lost', 'answered', 'ended', 'quiet', 'control']);
  const { lost, answered, ended, quiet, control } = f.people as Record<string, Person>;
  expectStatus(await quiet!.browser.request('PATCH', '/api/v1/notification-preferences',
    { body: { channels: { invitation: { inApp: false } } } }), 200);
  const endedSession = await liveSessionStore(db).createOrGet(human(f.owner), f.place.id, f.anchor, randomUUID(), async () => {});

  // Hold the generator's cursor so every change below lands before it reads these events.
  const hold = await pool.connect();
  let released = false;
  const release = async () => {
    if (released) return;
    released = true;
    try { await hold.query('COMMIT'); } finally { hold.release(); }
  };
  try {
    await hold.query('BEGIN');
    await hold.query("SELECT seq FROM notification_cursor WHERE id = 'generator' FOR UPDATE");
    await invitations.invite(human(f.owner), f.session.id, lost!.id);
    const toAnswer = await invitations.invite(human(f.owner), f.session.id, answered!.id);
    await invitations.invite(human(f.owner), endedSession.id, ended!.id);
    await invitations.invite(human(f.owner), f.session.id, quiet!.id);
    await invitations.invite(human(f.owner), f.session.id, control!.id);

    await grantProject(human(f.owner), f.place.id, { principal: human(lost!), role: 'denied' }, db);
    await invitations.reply(human(answered!), toAnswer.id, 'later');
    await pool.query(`UPDATE live_sessions SET state = 'ended', ended_at = now() WHERE id = $1`, [endedSession.id]);
  } finally {
    await release();
  }

  await waitFor(async () => (await inbox(control!)).find((entry) => entry.reason === 'invitation'), 'the control invitation');
  await generatorCaughtUp();
  assert.deepEqual(await invitationRows(lost!.id), [], 'lost project access before generation');
  assert.deepEqual(await invitationRows(answered!.id), [], 'already answered before generation');
  assert.deepEqual(await invitationRows(ended!.id), [], 'session ended before generation');
  const quietRows = await invitationRows(quiet!.id);
  assert.equal(quietRows.length, 1, 'push stays on, so the row backs it');
  assert.equal(quietRows[0]!.in_inbox, false);
  assert.equal((await inbox(quiet!)).some((entry) => entry.reason === 'invitation'), false, 'invitation.inApp=false keeps it out of the inbox');
  assert.deepEqual(await invitationRows(f.owner.id), []);
});
