/** Project conversations and materials are visible only through current project access. */
export const projectConversationsPath = (projectId: string) => `/api/v1/projects/${projectId}/conversations`;
export const conversationPath = (conversationId: string) => `/api/v1/conversations/${conversationId}`;
export const conversationMessagesPath = (conversationId: string) => `${conversationPath(conversationId)}/messages`;
export const projectMaterialsPath = (projectId: string) => `/api/v1/projects/${projectId}/materials`;
export const materialPath = (materialId: string) => `/api/v1/materials/${materialId}`;
export const materialVersionPath = (materialId: string, version: number) => `${materialPath(materialId)}/versions/${version}`;

export interface MaterialSource {
  materialId: string;
  version: number;
}

export interface ConversationMessage {
  id: string;
  conversationId: string;
  authorId: string;
  body: string;
  source: MaterialSource | null;
  /** Monotonic per conversation, including concurrent sends. */
  sequence: number;
  createdAt: string;
}

export interface Conversation {
  id: string;
  projectId: string;
  workspaceId: string;
  audience: { kind: 'project'; projectId: string };
  createdBy: string;
  createdAt: string;
  messages: ConversationMessage[];
}

export interface ConversationSummary {
  id: string;
  projectId: string;
  createdBy: string;
  createdAt: string;
  lastMessageAt: string;
  lastMessageBody: string;
}

export interface SendMessageCommand {
  body: string;
  /** UUID generated by the client and reused only for retries of this same send. */
  clientMessageId: string;
  source?: MaterialSource;
}

export interface MaterialVersion {
  materialId: string;
  version: number;
  title: string;
  body: string;
  url: string | null;
  authorId: string;
  sourceDraft: { id: string; version: number } | null;
  createdAt: string;
}

export interface Material extends MaterialVersion {
  projectId: string;
  workspaceId: string;
  audience: { kind: 'project'; projectId: string };
  createdAt: string;
  updatedAt: string;
}

export interface CreateMaterialCommand {
  /** UUID generated by the client and reused only for retries of this publication. */
  clientMutationId: string;
  title: string;
  body?: string;
  url?: string;
  /** Publication copies exactly the selected text, never the whole private draft. */
  sourceDraftId?: string;
  sourceDraftVersion?: number;
}

export interface UpdateMaterialCommand {
  expectedVersion: number;
  title?: string;
  body?: string;
  url?: string | null;
}
