import { randomUUID } from 'node:crypto';
import type { IncomingMessage } from 'node:http';
import type { Duplex } from 'node:stream';
import WebSocket, { WebSocketServer } from 'ws';
import type { SessionContext, SessionResolver } from '../identity/session.js';
import type { UpgradeGate } from '../http/upgrades.js';

export const EDITING_PATH = '/api/v1/editing';
export const EDITING_FRAME_BYTES = 65_536;
const SOCKET_LIMIT = 32;
const ADMISSION_TIMEOUT_MS = 5_000;
const ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export interface EditingTarget { kind: 'map' | 'wiki'; id: string }
export interface EditingContext {
  target: EditingTarget;
  session: SessionContext;
  /** Transport identity generated by the server; never persistent receipt identity. */
  connectionId: string;
}
export interface EditingGateOptions {
  publicOrigin: string;
  sessions: Pick<SessionResolver, 'resolveSession'>;
  /** Current core resource use case/policy; invisible resources must remain opaque. */
  authorize(context: EditingContext): Promise<void>;
  /** Installs message/error handlers synchronously; protected delivery uses the SQL fence. */
  accept(socket: WebSocket, context: EditingContext): void;
}
export interface EditingGate extends UpgradeGate {
  close(): Promise<void>;
  readonly pending: number;
  readonly connected: number;
}

function refuse(socket: Duplex, status: number, text: string) {
  if (!socket.destroyed && socket.writable) {
    socket.end(`HTTP/1.1 ${status} ${text}\r\nConnection: close\r\nContent-Type: text/plain\r\nContent-Length: ${Buffer.byteLength(text)}\r\n\r\n${text}`);
  }
  socket.destroy();
}

/** Supported detached server: bounds do not change the existing stream/media receivers. */
export function editingGate(options: EditingGateOptions): EditingGate {
  // Public ws 8.22 options missing from the older pinned @types/ws declaration.
  // Keep their exact numeric types and retain checking of all other options.
  const serverOptions: NonNullable<ConstructorParameters<typeof WebSocketServer>[0]> & {
    closeTimeout: number; maxFragments: number; maxBufferedChunks: number;
  } = {
    noServer: true, maxPayload: EDITING_FRAME_BYTES, perMessageDeflate: false,
    maxFragments: 144, maxBufferedChunks: 144, closeTimeout: 1_000,
  };
  const server = new WebSocketServer(serverOptions);
  const reservations = new Set<Duplex>();
  const clients = new Set<WebSocket>();
  let closing = false;

  return {
    get pending() { return reservations.size; },
    get connected() { return clients.size; },
    handleUpgrade(request, socket, head) {
      let url: URL;
      try { url = new URL(request.url ?? '/', 'http://editing.invalid'); }
      catch { return false; }
      if (url.pathname !== EDITING_PATH) return false;
      socket.on('error', () => socket.destroy());
      if (closing) { refuse(socket, 503, 'Unavailable'); return true; }
      if (request.headers.origin !== options.publicOrigin) { refuse(socket, 403, 'Forbidden'); return true; }
      const kind = url.searchParams.get('kind');
      const id = url.searchParams.get('id');
      if ((kind !== 'map' && kind !== 'wiki') || !id || !ID.test(id)
        || url.searchParams.getAll('kind').length !== 1 || url.searchParams.getAll('id').length !== 1
        || [...url.searchParams.keys()].some((key) => key !== 'kind' && key !== 'id')) {
        refuse(socket, 400, 'Invalid resource'); return true;
      }
      if (reservations.size + clients.size >= SOCKET_LIMIT || head.byteLength > EDITING_FRAME_BYTES + 14) {
        refuse(socket, 503, 'Unavailable'); return true;
      }
      // Count authentication/access work before its first await, including aborted requests
      // until that finite database work settles. A new socket cannot bypass this admission cap.
      reservations.add(socket); socket.pause();
      let expired = false;
      const timer = setTimeout(() => { expired = true; refuse(socket, 503, 'Unavailable'); }, ADMISSION_TIMEOUT_MS);
      timer.unref();
      void (async () => {
        try {
          const session = await options.sessions.resolveSession(request.headers);
          if (!session || session.expiresAt.getTime() <= Date.now()) { refuse(socket, 401, 'Authentication required'); return; }
          if (closing || expired || socket.destroyed) return;
          const context: EditingContext = { target: { kind, id: id.toLowerCase() }, session, connectionId: randomUUID() };
          try { await options.authorize(context); }
          catch { refuse(socket, 404, 'Not Found'); return; }
          if (session.expiresAt.getTime() <= Date.now()) { refuse(socket, 401, 'Authentication required'); return; }
          if (closing || expired || socket.destroyed) return;
          server.handleUpgrade(request, socket, head, (client) => {
            clients.add(client);
            client.on('error', () => client.terminate());
            client.once('close', () => clients.delete(client));
            try { options.accept(client, context); }
            catch { client.terminate(); }
            // Explicitly resume only after synchronous listener installation; test initial head frames.
            socket.resume();
          });
        } catch { refuse(socket, 503, 'Unavailable'); }
        finally { clearTimeout(timer); reservations.delete(socket); }
      })();
      return true;
    },
    async close() {
      closing = true;
      for (const socket of reservations) socket.destroy();
      for (const client of clients) client.terminate();
      await new Promise<void>((resolve) => server.close(() => resolve()));
    },
  };
}
