/** Project conversations and materials are visible only through current project access. */
export const projectConversationsPath = (projectId: string) => `/api/v1/projects/${projectId}/conversations`;
export const conversationPath = (conversationId: string) => `/api/v1/conversations/${conversationId}`;
export const conversationMessagesPath = (conversationId: string) => `${conversationPath(conversationId)}/messages`;
export const projectMaterialsPath = (projectId: string) => `/api/v1/projects/${projectId}/materials`;
export const materialPath = (materialId: string) => `/api/v1/materials/${materialId}`;
export const materialVersionPath = (materialId: string, version: number) => `${materialPath(materialId)}/versions/${version}`;

export interface MaterialSource {
  materialId: string;
  version: number;
}

/**
 * What an explicit native effect contributed to a canonical task thread (#154). Ordinary text carries
 * no marker, so the JSON of every existing message is unchanged. A result contribution names the one
 * canonical result; its finding, evidence and sources come from that result's ordinary authorized API.
 */
export type MessageContribution =
  | { kind: 'blocker' | 'handoff' }
  | { kind: 'result'; resultId: string };

export interface ConversationMessageFields {
  id: string;
  conversationId: string;
  body: string;
  source: MaterialSource | null;
  /** Monotonic per conversation, including concurrent sends. */
  sequence: number;
  createdAt: string;
  /** Present only for a saved blocker, a published result or an explicit public handoff. */
  contribution?: MessageContribution;
}

export type MessageIdentity =
  | { authorId: string; author?: never }
  | { authorId: null; author: { kind: 'agent'; id: string; name?: string } };
/** Existing human JSON is unchanged; agents never occupy a human account field. */
export type ConversationMessage = ConversationMessageFields & MessageIdentity;
export type HumanConversationMessage = ConversationMessageFields & { authorId: string; author?: never };
export type ConversationIdentity =
  | { createdBy: string; createdByActor?: never }
  | { createdBy: null; createdByActor: { kind: 'agent'; id: string; name?: string } };

export interface ConversationFields {
  id: string;
  projectId: string;
  workspaceId: string;
  audience: { kind: 'project'; projectId: string };
  createdAt: string;
  /** Stable discussion label from the opening message. */
  firstMessageBody: string;
  messages: ConversationMessage[];
  messagePage: {
    /** True when messages with a lower sequence can be fetched. */
    hasMoreBefore: boolean;
    nextBeforeSequence: number | null;
    limit: number;
  };
}
export type Conversation = ConversationFields & ConversationIdentity;

/** Stable, newest-first window returned in ascending display order. */
export interface ConversationWindowQuery {
  /** 1–100, default 50. */
  limit?: number;
  /** Fetch messages with sequence lower than this cursor. */
  beforeSequence?: number;
}

export interface ConversationSummaryFields {
  id: string;
  projectId: string;
  createdAt: string;
  /** Stable discussion label: the first message, even as newer replies arrive. */
  firstMessageBody: string;
  lastMessageAt: string;
  lastMessageBody: string;
}
export type ConversationSummary = ConversationSummaryFields & ConversationIdentity;

/**
 * One project conversation (UI116-1, 2026-10-02): a chronological stream of roots. A root is the
 * opening message (sequence 1) of a stored conversation; its later messages are that root's
 * one-level thread, read through `GET /api/v1/conversations/:id`.
 */
export const projectConversationRootsPath = (projectId: string) => `/api/v1/projects/${projectId}/conversation-roots`;

export interface ConversationRoot {
  conversationId: string;
  /** The root message, sequence 1, with its true author, time, source and contribution. */
  message: ConversationMessage;
  /** Messages after the root in its thread. */
  replyCount: number;
  lastReplyAt: string | null;
}

/** Stable, newest-first window of roots returned in ascending display order. */
export interface ConversationRootQuery {
  /** 1–100, default 50. */
  limit?: number;
  /** Fetch roots older than this conversation of the same project. */
  before?: string;
}

export interface ConversationRootWindow {
  projectId: string;
  roots: ConversationRoot[];
  rootPage: {
    /** True when older roots can be fetched with `before: nextBefore`. */
    hasMoreBefore: boolean;
    nextBefore: string | null;
    limit: number;
  };
}

export interface SendMessageCommand {
  body: string;
  /** UUID generated by the client and reused only for retries of this same send. */
  clientMessageId: string;
  source?: MaterialSource;
}

export interface MaterialVersion {
  materialId: string;
  version: number;
  title: string;
  body: string;
  url: string | null;
  authorId: string;
  sourceDraft: { id: string; version: number } | null;
  createdAt: string;
}

export interface Material extends MaterialVersion {
  /** `doc` for a project doc (#112); edit docs through the doc API. */
  kind: 'material' | 'doc';
  projectId: string;
  workspaceId: string;
  audience: { kind: 'project'; projectId: string };
  createdAt: string;
  updatedAt: string;
}

export interface CreateMaterialCommand {
  /** UUID generated by the client and reused only for retries of this publication. */
  clientMutationId: string;
  title: string;
  body?: string;
  url?: string;
  /** Publication copies exactly the selected text, never the whole private draft. */
  sourceDraftId?: string;
  sourceDraftVersion?: number;
}

export interface UpdateMaterialCommand {
  /** UUID reused when retrying this exact edit after a lost response. */
  clientMutationId: string;
  expectedVersion: number;
  title?: string;
  body?: string;
  url?: string | null;
}
